### ISSUE TITLE
What is the ply project license?

### ISSUE THREAD

**Issue by dmacvicar** [blangel/ply#5]
I can't figure out the license of the code from the git repository, which prevents eg. packaging it.

**Comment by blangel** [comment]
@dmacvicar great question. I've been meaning to update with this information.  It's released under Apache version 2.0 - http://www.apache.org/licenses/LICENSE-2.0
Are you planning on packaging it?

**Comment by dmacvicar** [comment]
Usually I package every stuff I am playing with in my home project (https://build.opensuse.org/project/show/home:dmacvicar) before playing with it.

In the case of Java building tools, it is very important to me that it is easy to package and bootstrap, given that maven is almost impossible (the build tool depends at build-time on almost the complete ecosystem it is supposed to build in the first place).

**Comment by blangel** [comment]
@dmacvicar sounds great. I definitely understand the Maven bloat frustrations. Ply has code to parse a pom file and doesn't depend upon Maven's own code to do this as it pulls in a giant tree of dependencies.
Let me know if you have any issues/etc. Lots of functionality which needs documentation love and so may be hard to understand without some guidance.

I'll close this in a day or so if I haven't heard from you.
